import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Logo from "@/components/Logo";
import "./globals.css";
import { NavMenu } from "@/components/NavMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Up Task",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100`}
        cz-shortcut-listen="true"
      >
        <header className="bg-gray-800 py-5">
          <div className="max-w-screen-2xl mx-auto flex flex-col lg:flex-row justify-between items-center">
            <div className="relative w-64 h-16">
              <Logo />
            </div>
            <NavMenu />
          </div>
        </header>

        <section className="max-w-screen-2xl mx-auto mt-10 p-5">
          {children}
        </section>

        <footer className="py-5">
          <p className="text-center">
            © Todos los derechos reservados {new Date().getFullYear()}
          </p>
        </footer>
      </body>
    </html>
  );
}
